### ISSUE TITLE
ERROR when installing pygrappa in a singularity image

### ISSUE THREAD

**Issue by zaccharieramzi** [mckib2/pygrappa#81]
I am trying to have `pygrappa` installed in a singularity image, and I have the following error when installing:

```
Building wheels for collected packages: pygrappa
  Building wheel for pygrappa (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vq3t3qkm
       cwd: /tmp/pip-install-c7s46can/pygrappa/
  Complete output (109 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "pygrappa.cgrappa" sources
  building extension "pygrappa.grog_powers" sources
  building extension "pygrappa.grog_gridding" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/benchmarks
  copying benchmarks/__init__.py -> build/lib.linux-x86_64-3.6/benchmarks
  copying benchmarks/benchmark.py -> build/lib.linux-x86_64-3.6/benchmarks
  creating build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/cgsense.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/grappa_kdtree.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/lustig_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/simple_pruno.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/ttgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/gfactor.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/radialgrappaop.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/seggrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/pruno.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/kernels.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/nlgrappa_matlab.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/nlgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/slicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/sense1d.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/splitslicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/ncgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/tgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/pars.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/kspa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/grappaop.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/grog.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  copying pygrappa/grappa.py -> build/lib.linux-x86_64-3.6/pygrappa
  creating build/lib.linux-x86_64-3.6/utils
  copying utils/__init__.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/radial_sms_sim.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/gridder.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/find_acs.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/disjoint_csm.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/findRectangle2d.py -> build/lib.linux-x86_64-3.6/utils
  copying utils/gaussian_csm.py -> build/lib.linux-x86_64-3.6/utils
  creating build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_cgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/helpers.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  copying pygrappa/tests/test_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
  creating build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_splitslicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_gfactor.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_nlgrappa_matlab.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_gridding.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/mdgrappa_autofind_calib.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/inverse_grog.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_tgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_cgsense.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_pars.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/primefac_grog_cardiac.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/primefac_grog.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/use_memmap.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_grappaop.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_radialgrappaop.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/bart_pars.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/7t_knee_data.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_nlgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/tikhonov_regularization.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_ttgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/bart_kspa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_ncgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_seggrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_sense1d.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_cgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  copying pygrappa/examples/basic_slicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  building 'pygrappa.cgrappa' extension
  compiling C++ sources
  C compiler: x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
  
  creating build/temp.linux-x86_64-3.6/src
  compile options: '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./src/ -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c'
  x86_64-linux-gnu-g++: ./src/cgrappa.cpp
  x86_64-linux-gnu-g++: ./src/get_sampling_patterns.cpp
  error: Command "x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./src/ -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c ./src/cgrappa.cpp -o build/temp.linux-x86_64-3.6/src/cgrappa.o -MMD -MF build/temp.linux-x86_64-3.6/src/cgrappa.o.d" failed with exit status 127
  ----------------------------------------
  ERROR: Failed building wheel for pygrappa
  Running setup.py clean for pygrappa
Failed to build pygrappa
Installing collected packages: scipy, six, cycler, kiwisolver, pyparsing, python-dateutil, matplotlib, tqdm, pillow, imageio, tifffile, PyWavelets, decorator, networkx, scikit-image, ssfp, phantominator, pygrappa
    Running setup.py install for pygrappa ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7hvszict/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pygrappa
         cwd: /tmp/pip-install-c7s46can/pygrappa/
    Complete output (109 lines):
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "pygrappa.cgrappa" sources
    building extension "pygrappa.grog_powers" sources
    building extension "pygrappa.grog_gridding" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/benchmarks
    copying benchmarks/__init__.py -> build/lib.linux-x86_64-3.6/benchmarks
    copying benchmarks/benchmark.py -> build/lib.linux-x86_64-3.6/benchmarks
    creating build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/cgsense.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/grappa_kdtree.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/lustig_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/simple_pruno.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/ttgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/gfactor.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/radialgrappaop.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/seggrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/pruno.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/kernels.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/nlgrappa_matlab.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/nlgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/slicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/sense1d.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/splitslicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/ncgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/tgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/pars.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/kspa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/grappaop.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/grog.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    copying pygrappa/grappa.py -> build/lib.linux-x86_64-3.6/pygrappa
    creating build/lib.linux-x86_64-3.6/utils
    copying utils/__init__.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/radial_sms_sim.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/gridder.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/find_acs.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/disjoint_csm.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/findRectangle2d.py -> build/lib.linux-x86_64-3.6/utils
    copying utils/gaussian_csm.py -> build/lib.linux-x86_64-3.6/utils
    creating build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_cgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/helpers.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    copying pygrappa/tests/test_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa/tests
    creating build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_splitslicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_gfactor.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_nlgrappa_matlab.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_gridding.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/mdgrappa_autofind_calib.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/inverse_grog.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_tgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_cgsense.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_grappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/__init__.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_mdgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_pars.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/primefac_grog_cardiac.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/primefac_grog.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_hpgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/use_memmap.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_grappaop.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_radialgrappaop.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/bart_pars.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/7t_knee_data.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_vcgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_nlgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/tikhonov_regularization.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_ttgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/bart_kspa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_ncgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_seggrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_sense1d.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_cgrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_igrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    copying pygrappa/examples/basic_slicegrappa.py -> build/lib.linux-x86_64-3.6/pygrappa/examples
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    building 'pygrappa.cgrappa' extension
    compiling C++ sources
    C compiler: x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    
    creating build/temp.linux-x86_64-3.6/src
    compile options: '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./src/ -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c'
    x86_64-linux-gnu-g++: ./src/cgrappa.cpp
    x86_64-linux-gnu-g++: ./src/get_sampling_patterns.cpp
    error: Command "x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./src/ -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c ./src/cgrappa.cpp -o build/temp.linux-x86_64-3.6/src/cgrappa.o -MMD -MF build/temp.linux-x86_64-3.6/src/cgrappa.o.d" failed with exit status 127
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7s46can/pygrappa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7hvszict/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pygrappa Check the logs for full command output.
```

I find it very hard to read and I am wondering whether this error rings a bell for anyone.

This is the singularity recipe file I used:

```
Bootstrap: docker
From: ubuntu:16.04


%help
    Singularity container for GRAPPA.

%post
  apt update -y
  apt install software-properties-common curl -y
  apt update -y
  add-apt-repository ppa:deadsnakes/ppa -y
  apt update -y
  apt install python3.6 python3.6-dev -y
  curl https://bootstrap.pypa.io/get-pip.py | python3.6
  pip3 install numpy
  pip3 install pygrappa
```

**Comment by zaccharieramzi** [comment]
I managed to get access to the logs by installing everything but pygrappa and then in the container, trying to install pygrappa. The error is as follows:

```
2020-07-01T18:08:57,312 Exception information:
2020-07-01T18:08:57,312 Traceback (most recent call last):
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 841, in install
2020-07-01T18:08:57,312     req_description=str(self.req),
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 86, in install
2020-07-01T18:08:57,312     raise LegacyInstallFailure
2020-07-01T18:08:57,312 pip._internal.operations.install.legacy.LegacyInstallFailure
2020-07-01T18:08:57,312 
2020-07-01T18:08:57,312 During handling of the above exception, another exception occurred:
2020-07-01T18:08:57,312 
2020-07-01T18:08:57,312 Traceback (most recent call last):
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 188, in _main
2020-07-01T18:08:57,312     status = self.run(options, args)
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
2020-07-01T18:08:57,312     return func(self, options, args)
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 407, in run
2020-07-01T18:08:57,312     use_user_site=options.use_user_site,
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
2020-07-01T18:08:57,312     **kwargs
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 845, in install
2020-07-01T18:08:57,312     six.reraise(*exc.parent)
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/six.py", line 703, in reraise
2020-07-01T18:08:57,312     raise value
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 76, in install
2020-07-01T18:08:57,312     cwd=unpacked_source_directory,
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 274, in runner
2020-07-01T18:08:57,312     spinner=spinner,
2020-07-01T18:08:57,312   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
2020-07-01T18:08:57,312     raise InstallationError(exc_msg)
2020-07-01T18:08:57,312 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-frxa9xn1/pygrappa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-frxa9xn1/pygrappa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k9cnozx8/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pygrappa Check the logs for full command output.
```

**Comment by mckib2** [comment]
I have not seen this error before, but I can take a look at it later today.

**Comment by remmaria** [comment]
> I have not seen this error before, but I can take a look at it later today.

I had the same issue here. I would really appreciate that! =)))

**Comment by mckib2** [comment]
> Bootstrap: docker
From: ubuntu:16.04

Is there a reason you're using Ubuntu 16 instead of 18 or 20?  I'm just starting to take a look at this.

**Comment by mckib2** [comment]
As a work around, this recipe based on Ubuntu 18 appears to install without a hitch:
```
Bootstrap: docker
From: ubuntu:18.04


%help
    Singularity container for GRAPPA.

%post
  apt update -y
  apt-get install -y python3-pip
  pip3 install numpy
  pip3 install pygrappa
```

**Comment by mckib2** [comment]
@zaccharieramzi and @remmaria The following adjustments to the singularity recipe are working for me:
```
Bootstrap: docker
From: ubuntu:16.04


%help
    Singularity container for GRAPPA.

%post
  apt update -y
  apt install software-properties-common curl build-essential -y
  apt update -y
  add-apt-repository ppa:deadsnakes/ppa -y
  apt update -y
  apt install -y python3.6 python3.6-dev
  curl https://bootstrap.pypa.io/get-pip.py | python3.6
  python3.6 -m pip install numpy
  python3.6 -m pip install pygrappa
```

I am still not sure what the underlying problem was, but I hope this will help.  Let me know if it does not work for you

**Comment by zaccharieramzi** [comment]
@mckib2 thanks your fixes worked for me.
